spring:
  datasource:
    url: jdbc:mysql://localhost:3306/search_engine
    username: root
    password: 89257044306mV
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    database: MYSQL
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: create
  thymeleaf:
    cache: false
#    prefix: classpath:/templates


sites:
  - url: https://www.lenta.ru
    name: Лента.ру

user-agent: DuckSearchBot

path: /admin

