
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/search_engine
    username: root
    password: 89257044306mV
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 100
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: update
  thymeleaf:
    cache: false
  jta:
    atomikos:
      properties:
        enable-logging: true
#    prefix: classpath:/templates

local:
  path: /admin
  user-agent: DuckSearchBot
  sites:
#      - url:  https://www.playback.ru
#        name: PlayBack
#      - url: https://lentgga.ru
#        name: Ленggта.ру
#      - url: https://www.svetlovka.ru
#        name: Библиотека Светловка
#      - url: https://www.lutherancathedral.ru
#        name: Собор Петра и Павла
#      - url: https://volochek.life
#        name: Волчёк



