spring:
  datasource:
    url: jdbc:mysql://localhost:3306/search_engine
    username: root
    password: 89257044306mV
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 100
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: update
  thymeleaf:
    cache: false
  jta:
    atomikos:
      properties:
        enable-logging: true
    prefix: classpath:/templates
  mail:
    host: smtp.gmail.com
    port: 587
    username: search.engine.mephi12@gmail.com
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    password: ivdvuyxxskxidlee
local:
  jwt:
    secret:
      access: qBTmv4oXFFR2GwjexDJ4t6fsIUIUhhXqlktXjXdkcyygs8nPVEwMfo29VDRRepYDVV5IkIxBMzr7OEHXEHd37w==
      refresh: zL1HB3Pch05Avfynovxrf/kpF9O2m4NCWKJUjEp27s9J2jEG3ifiKCGylaZ8fDeoONSTJP/wAzKawB8F9rOMNg==
  path: /admin
  user-agent: DuckSearchBot



